USE [master]
GO

/****** Object:  Database [CPUData]    Script Date: 9/25/2014 2:15:48 AM ******/
CREATE DATABASE [CPUData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CPUData', FILENAME = N'D:\SQL2014\MSSQL12.MSSQLSERVER\MSSQL\DATA\CPUData.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CPUData_log', FILENAME = N'D:\SQL2014\MSSQL12.MSSQLSERVER\MSSQL\DATA\CPUData_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CPUData] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CPUData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CPUData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CPUData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CPUData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CPUData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CPUData] SET ARITHABORT OFF 
GO

ALTER DATABASE [CPUData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CPUData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CPUData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CPUData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CPUData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CPUData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CPUData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CPUData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CPUData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CPUData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CPUData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CPUData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CPUData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CPUData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CPUData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CPUData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CPUData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CPUData] SET RECOVERY FULL 
GO

ALTER DATABASE [CPUData] SET  MULTI_USER 
GO

ALTER DATABASE [CPUData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CPUData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CPUData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CPUData] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CPUData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CPUData] SET  READ_WRITE 
GO

